services:
  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    volumes:
      - ./user-service/data:/app/data
    restart: unless-stopped

  songs-service:
    build: ./songs-service
    ports:
      - "8081:8081"
    volumes:
      - ./songs-service/data:/app/data
    restart: unless-stopped

  health-checker-service:
    build: ./health-checker-service
    ports:
      - "8082:8082"
    restart: unless-stopped
