spring.application.name=sqlite

spring.datasource.url=jdbc:sqlite:./data/mydb.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=1

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

management.endpoint.health.show-details=always

spring.data.web.pageable.max-page-size=100
